spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resource server:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/fitnes_OAuth2/protocol/openid-connect/certs
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 8084
