spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ActivityService
      collation: simple
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange:
    name: fitness.exchange
  routing:
    key: activity.tracking
  queue: activity.queue

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
