server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/FitnessRecommendations
      database: recommendations
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  gemini:
    api:
      url: ${GEMINI_API_URL}
      key: ${GEMINI_API_KEY}

rabbitmq:
  exchange:
    name: fitness.exchange
  routing:
    key: activity.tracking
  queue: activity.queue

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
