server.port:8082

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost

spring.data.mongodb.uri=mongodb://localhost:27017/FitnessRecommendations
spring.data.mongodb.database=recommendations
eureka.instance.prefer-ip-address=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
rabbitmq.exchange.name=fitness.exchange
rabbitmq.routing.key=activity.tracking
rabbitmq.queue=activity.queue

spring.gemini.api.url=${GEMINI_API_URL}
spring.gemini.api.key=${GEMINI_API_KEY}