spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true    # allow using service names from Eureka
#          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**
        - id: activity-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/activities/**
        - id: ai-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/recommendations/**

server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
